version: '2'


services:

  web2:
    build:
      context: ./Round_Robin
      dockerfile: Dockerfile
    links:
      - loadbalancer1
      - loadbalancer2
      - loadbalancer3
    container_name: robin
    ports:
      - "4568:6000"

  loadbalancer1:
    build:
      context: ./LogService
      dockerfile: Dockerfile
    container_name: log1
    environment:
      - PORT=8090
    links:
      - webdb
    ports:
      - "8090:6000"
  loadbalancer2:
    build:
      context: ./LogService
      dockerfile: Dockerfile
    container_name: log2
    environment:
      - PORT=8091
    links:
      - webdb
    ports:
      - "8091:6000"
  loadbalancer3:
    build:
      context: ./LogService
      dockerfile: Dockerfile
    container_name: log3
    environment:
      - PORT=8092
    links:
      - webdb
    ports:
      - "8092:6000"

  webdb:
    build:
      context: ./MongoDb
      dockerfile: Dockerfile
    container_name: web
    environment:
      - PORT=8087
    ports:
      - "8087:6000"

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod


volumes:
  mongodb:
  mongodb_config:
